services:
  db:
    container_name: ${POSTGRES_DB_NAME}
    image: postgres:12-alpine
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
  
  pgadmin:
    depends_on:
      - db
    container_name: ${PGADMIN_NAME}
    image: dpage/pgadmin4:8
    ports:
      - 5050:80
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  
  # fastapi:
  #   depends_on:
  #     - db
  #   container_name: el-manjar-service-fastapi
  #   image: docker_fast_api_example_22
  #   ports:
  #     - "80:80"
  #   restart: always
  #   environment:
  #     POSTGRES_USERNAME: ${POSTGRES_USERNAME}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: ${POSTGRES_PORT}

volumes:
  postgres-vol:
  pgadmin-vol: